### ISSUE TITLE
Expanse data is not beeing updated

### ISSUE THREAD

**Issue by Z0pyrus** [jc9108/expanse#1] opened 2022-09-11 15:32 UTC
After some time I've run into an issue where the data is not getting updated anymore: `last updated: 15h ago`. I've imported my Reddit data with csv files which lead to an overall saved count of 4410. Also, my pihole fetched about 38000 requests to oauth.reddit.com.
In the console I got this error while it's trying to update the data:
```
RequestError: Error: ETIMEDOUT
    at new RequestError (/backend/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/backend/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/backend/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/backend/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Timeout.<anonymous> (/backend/node_modules/request/request.js:851:16)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  cause: Error: ETIMEDOUT
      at Timeout.<anonymous> (/backend/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    code: 'ETIMEDOUT',
    connect: true
  },
  error: Error: ETIMEDOUT
      at Timeout.<anonymous> (/backend/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    code: 'ETIMEDOUT',
    connect: true
  },
      
  options: {
    gzip: true,
    json: true,
    headers: { 'user-agent': 'web:expanse:v=1.0.0 (hosted by u/myusername)' },
    baseUrl: 'https://oauth.reddit.com',
      
{
      raw_json: 1,
      count: 9999,
      limit: 9007199254740991,
      before: 't3_xazslb'
    },
    auth: { bearer: 'hidden for privacy' },
    resolveWithFullResponse: true,
    timeout: 30000,
    transform: [Function: transform],
    uri: 'user/myusername/upvoted',
    method: 'GET',
    callback: [Function: RP$callback],
    simple: true,
    transform2xxOnly: false
  },
  response: undefined
}
```
At the moment I try to recreate the error:

I've imported csv files to it (I think all of the possible ones). After that it didn't updated anymore.

**Comment by Z0pyrus** [comment] 2022-09-11 15:38
After trying to reproduce it, I get the error after logging in as well. Am I maybe banned for api calls for reddit?

**Comment by Z0pyrus** [comment] 2022-09-11 17:03
I think limiting the calls my help because in the Reddit API docs is written that: “Clients connecting via [OAuth2](https://github.com/reddit-archive/reddit/wiki/OAuth2) may make up to 60 requests per minute”. So maybe I'm "banned"

**Comment by jc9108** [comment] 2022-09-11 21:10
> hmm ive never run into this while testing. i just tested again with an import of over 20k items and its still as expected
>
> ![image](https://user-images.githubusercontent.com/31039318/189533183-ab957f04-975c-4bb9-b865-717d18c63b85.png)
>
> from that error message i cant tell what caused it, other than sometimes reddit api is unreliable and you get undefined response, but that should not crash the update cycle. is there anything else specific you did before this happened? also, the request timeout error might possibly be on your device's end?
>
> ill leave an instance up for now and see if it runs into this

**Comment by jc9108** [comment] 2022-09-11 21:14
> I've imported csv files to it (I think all of the possible ones). After that it didn't updated anymore.

i tested this and had no issue. so i cant really debug it. i guess we can wait for more ppl to use expanse and see if they get this too. but for now i think this might be a network issue on your device's end? are you sure your box didnt get disconnected to the internet as the request is being timed out?

**Comment by jc9108** [comment] 2022-09-11 21:19
> While Logging in the first time it is stuck at some point which can be solved by reloading the page. There is also a new error in the console

the `dne` error and 401 is intentional, if you deleted the db. this happens bc the cookie has a user session but the db doesnt have the user anymore. it is intentional and from expanse, not from reddit

**Comment by Z0pyrus** [comment] 2022-09-11 21:20
I've tested it about 5 times now, and I always get the same error even during the initial run of expanse. I also changed my external IP address.
How long should be the session secret and encryption key be? Could be extreme long keys cause this? (128)

But like I said, I have a really "special" setup (raspberrypi 4, 8gb, docker in rootless mode on an SSD)

> the `dne` error and 401 is intentional, if you deleted the db. this happens bc the cookie has a user session but the db doesnt have the user anymore. it is intentional and from expanse, not from reddit

Ok, I think I've got this error after deleting my cookies.

**Comment by jc9108** [comment] 2022-09-11 21:22
> I think limiting the calls my help because in the [Reddit API docs](https://github.com/reddit-archive/reddit/wiki/API#rules) is written that: “Clients connecting via [OAuth2](https://github.com/reddit-archive/reddit/wiki/OAuth2) may make up to 60 requests per minute”. So maybe I'm "banned".

no, i do not think you are banned from the api. all requests from expanse are made from an reddit api wrapper (snoowrap) which has has [built-in ratelimit protection](https://not-an-aardvark.github.io/snoowrap/index.html)

<br/>

> During my first install I scrolled to the bottom of my saved posts. Maybe this could have triggered a ban if each entry was loaded somehow but this is very unlikely.

this also could not have triggered a ban since scrolling your categories on expanse only retrieves items from your expanse db, it doesnt request them from reddit at all

**Comment by jc9108** [comment] 2022-09-11 21:30
> But are 40.000+ requests to reddit normal? (~24h)

this is definitely possible, especially if you had a lot of items to import. but the ratelimit should not be exceeded like i said due to the ratelimit protection as well as how i implemented the import process (imports are split up into intervals to ensure it does not attempt to request past the ratelimit). and 40,000 requests being split up over 24 hours does not exceed the ratelimit of 60req/min

once they are done importing, there should be less requests too. and if you have multiple users, each user has their own ratelimit

**Comment by Z0pyrus** [comment] 2022-09-11 21:32
> each user has their own ratelimit

Also if the users are in the same Home Network?

**Comment by jc9108** [comment] 2022-09-11 21:34
yep

**Comment by Z0pyrus** [comment] 2022-09-12 00:59
I maybe found the culprit: It could be my reverse proxy (NGINX Proxy Manager). I will try to use the up only. ([this helped me](https://stackoverflow.com/questions/33350604/what-could-cause-connect-etimedout-error-when-the-url-is-working-in-browser))

**Comment by jc9108** [comment] 2022-09-12 01:25
it seems that both you and @rickcecil in #2 are using nginx proxy manager so i think it has something to do with that

for reference i am also using nginx (but with a manual setup, not nginx proxy manager) as a reverse proxy for eternity, and it does work fine

**Comment by Z0pyrus** [comment] 2022-09-12 01:46
Maybe it has something to do with my pihole. I'm testing expanse on wsl right now, and I get another error which is similar. Maybe it's my dns (unbound) I will investigate more in this tomorrow.

**Comment by jc9108** [comment] 2022-09-12 08:49
see my edit above. btw what are you using to check outgoing requests? and are you able to confirm if they are all/mostly failed requests? and the cause of failure?

**Comment by Z0pyrus** [comment] 2022-09-12 14:36
I only see the failure in the logs. I'm also running a pihole where I can see how many requests were made to Reddit. But none of them failed.

After testing expanse on my Laptop on different networks I think I know why some requests are failing: It might be my pihole + unbound setup. But I don't know why this is happening. 

After more invastigation I highly think it is my Unbound DNS causing this error. 

The easiest solution bmight be to just set 9.9.9.9 (or any other DNS server) as the primery dns server for this container.

**Comment by jc9108** [comment] 2022-09-12 15:18
ok. ive had an instance on wsl2 running for over 24h at this point with over 50k items imported, everything is fine. pretty certain this is not a problem with expanse so im just gonna close this now. if you fully figure it out feel free to comment after though, it might help others with a similar setup/config as you

404 is not found, so prob those items were deleted from reddit

**Closed by jc9108** 2022-09-12 15:18 UTC
Labels: bug, invalid

**Comment by Keagel** [comment] 2022-09-26 09:46
I'm not sure if it's related to this issue as there are no errors in the logs, but my content isn't being updated either. Here's an excerpt of the logs:

```
last Thursday at 9:49:37 PM updating user (Keagel)
last Thursday at 9:49:39 PM updated user (Keagel)
last Friday at 11:40:53 AM backed up db to file (23-09-2022_09꞉40꞉53꞉AM_UTC.sql)
last Saturday at 11:40:53 AM backed up db to file (24-09-2022_09꞉40꞉53꞉AM_UTC.sql)
yesterday at 11:40:53 AM backed up db to file (25-09-2022_09꞉40꞉53꞉AM_UTC.sql)
today at 11:27:37 AM socket (1W4pcrj0y8-iKP_OAACZ) connected
today at 11:27:37 AM getting user (Keagel)
today at 11:27:37 AM deserialized user (Keagel)
```

Restarting the container forces the updates though.

**Comment by jc9108** [comment] 2022-09-26 10:02
this issue was not a problem in expanse itself, it had to do with the end-user's network configs. if you think your issue is with expanse, please open a new issue for it
