### ISSUE TITLE
Content isn't getting updated

### ISSUE THREAD

**Issue by Keagel** [jc9108/expanse#16] opened 2022-09-26 10:04 UTC
The content of my user accounts stopped getting updated after a day. I set it up on Wednesday and the last update occurred on Thursday. Here's an excerpt of the logs:

```
last Thursday at 9:49:37 PM updating user (Keagel)
last Thursday at 9:49:39 PM updated user (Keagel)
last Friday at 11:40:53 AM backed up db to file (23-09-2022_09꞉40꞉53꞉AM_UTC.sql)
last Saturday at 11:40:53 AM backed up db to file (24-09-2022_09꞉40꞉53꞉AM_UTC.sql)
yesterday at 11:40:53 AM backed up db to file (25-09-2022_09꞉40꞉53꞉AM_UTC.sql)
today at 11:27:37 AM socket (1W4pcrj0y8-iKP_OAACZ) connected
today at 11:27:37 AM getting user (Keagel)
today at 11:27:37 AM deserialized user (Keagel)
```

Restarting the container forces the updates though.

_Originally posted by @Keagel in https://github.com/jc9108/expanse/issues/1#issuecomment-1257775758_

**Comment by jc9108** [comment] 2022-09-26 10:09
those logs indicate that the update cycle stopped since last thursday. if there are no error logs, i'm not aware of anything else that could've stopped it.

is this a one-time thing or did it happen again after you restarted the container?

**Comment by Keagel** [comment] 2022-09-26 10:19
I restarted the container only 30 minutes ago so I don't know yet. I'm guessing something hung after the call to `user.update()`: https://github.com/jc9108/expanse/blob/8f100b837ac84f5ffe5e27937d31f06d2750e0f6/backend/model/user.mjs#L595 as the log doesn't show the "update all completed" message it should. Maybe something to do with the socket?

**Comment by jc9108** [comment] 2022-09-26 10:49
> I'm guessing something hung after the call to `user.update()`

there arent any asynchronous operations after line 595 in that block, so nothing could have hung after that. but we do know that the `user.update` was successful since it logged "updated user" from [line 450](https://github.com/jc9108/expanse/blob/8f100b837ac84f5ffe5e27937d31f06d2750e0f6/backend/model/user.mjs#L450). if there was an error in the synchronous operations after that, it shouldve been caught and logged to stderr by the `try catch` block regardless.

<br/>

anyhow, it's not clear how this occured. let's wait a while to see if it happens again or if anyone else has this issue.

**Comment by jc9108** [comment] 2022-09-26 10:57
> I'm guessing something hung after the call to `user.update()`

there arent any asynchronous operations after line 595 in that block, so nothing could have hung after that. but we do know that the `user.update` was successful since it logged "updated user" from [line 450](https://github.com/jc9108/expanse/blob/8f100b837ac84f5ffe5e27937d31f06d2750e0f6/backend/model/user.mjs#L450). if there was an error in the synchronous operations after that, it shouldve been caught and logged to stderr by the `try catch` block regardless.

<br/>

anyhow, it's not clear how this occurred. let's wait a while to see if it happens again or if anyone else has this issue and can provide more info on how to reproduce it.

**Comment by Keagel** [comment] 2022-10-20 19:43
Unfortunately it happened again yesterday after three weeks of everything working normally. Hangs at the same step of the updating process.

```
yesterday at 9:20:34 AM getting user (Keagel)
yesterday at 9:20:34 AM updating user (Keagel)
yesterday at 9:20:36 AM updated user (Keagel)
yesterday at 9:20:36 AM update all completed
yesterday at 9:21:33 AM getting user (Keagel)
yesterday at 9:21:33 AM updating user (Keagel)
yesterday at 12:14:41 PM backed up db to file (19-10-2022_10꞉14꞉41꞉AM_UTC.sql)
yesterday at 12:14:41 PM deleted oldest db backup (19-10-2022_10꞉14꞉41꞉AM_UTC.sql) past limit (5)
today at 12:14:41 PM backed up db to file (20-10-2022_10꞉14꞉41꞉AM_UTC.sql)
today at 12:14:41 PM deleted oldest db backup (20-10-2022_10꞉14꞉41꞉AM_UTC.sql) past limit (5)
today at 5:47:01 PM socket (lvsdPUCgQph_obTrAAH0) connected
```

**Comment by jc9108** [comment] 2022-10-29 11:53
still not clear how to reproduce this, so i cant really do anything about it. there also seems to be something else weird going on with your instance if these new logs are accurate. it shows that new backups are immediately being deleted, instead of the 6th oldest backup being deleted. this is how it should behave (with backup interval set to 5s for demonstration purposes)::
![image](https://user-images.githubusercontent.com/31039318/198828891-79845345-4535-4aee-890e-bf3e3e5a7278.png)

you are using the official image?

**Comment by Keagel** [comment] 2022-11-01 17:58
I'm using the official image. As for the backup issue, I'm not sure what's happening. Yesterday's logs show that it's deleting an older backup:

```
yesterday at 8:44:35 PM backed up db to file (31-10-2022_07꞉44꞉35꞉PM_UTC.sql)
yesterday at 8:44:35 PM deleted oldest db backup (28-10-2022_07꞉44꞉35꞉PM_UTC.sql) past limit (5)
```

But as you can see, the directory contains two much older backup files that somehow don't get selected as the oldest files in this function: https://github.com/jc9108/expanse/blob/b2c66659f26a364482a6544bebd6c736d8c6f05d/backend/model/file.mjs#L104

```
$ ls -lah ~/docker/appdata/expanse/backups
total 7.8M
drwxr-xr-x+ 2 root root 4.0K Oct 31 19:44 .
drwxr-xr-x+ 4 root root 4.0K Sep 21 09:36 ..
-rw-rw-r--+ 1 root root 1.5M Sep 29 10:14 29-09-2022_10꞉14꞉40꞉AM_UTC.sql
-rw-rw-r--+ 1 root root 1.6M Oct 29 19:44 29-10-2022_07꞉44꞉35꞉PM_UTC.sql
-rw-rw-r--+ 1 root root 1.5M Sep 30 10:14 30-09-2022_10꞉14꞉40꞉AM_UTC.sql
-rw-rw-r--+ 1 root root 1.6M Oct 30 19:44 30-10-2022_07꞉44꞉35꞉PM_UTC.sql
-rw-rw-r--+ 1 root root 1.6M Oct 31 19:44 31-10-2022_07꞉44꞉35꞉PM_UTC.sql
```

**Comment by jc9108** [comment] 2022-11-01 22:56
thanks. that function has been fixed with https://github.com/jc9108/expanse/commit/9ba2e4b062bd07d24aedab7fdbe6994505794c59

**Comment by jc9108** [comment] 2022-12-11 04:37
reopen if reproducible (with steps)

**Closed by jc9108** 2022-12-11 04:37 UTC
Labels: bug, no repro
