### ISSUE TITLE
unknown shorthand flag: 'f' in -f

### ISSUE THREAD

**Issue by moorsey** [jc9108/expanse#35] opened 2023-04-14 08:43 UTC
Get this when running:

`sh ./run.sh prod up`

**Comment by sugoidogo** [comment] 2023-04-15 08:00
https://github.com/docker/compose/issues/8986

Looks like this issue is mainly caused by docker installation issues. Can you double check you have docker-compose installed and up to date?

**Comment by sugoidogo** [comment] 2023-04-15 08:04
Also, looks like a duplicate of #31 (with a better title)

**Comment by sugoidogo** [comment] 2023-04-20 12:17
https://github.com/docker/compose/issues/8986#issuecomment-1266572352

Looks like you have compose v1, and you need compose v2. You may need to add upstream repos.

**Comment by jc9108** [comment] 2023-04-20 22:35
install the [latest docker and docker compose for your platform](https://docs.docker.com/engine/install). it'll be `docker compose`, not `docker-compose`

**Comment by jc9108** [comment] 2023-04-20 22:36
install the [latest docker engine and docker compose for your platform](https://docs.docker.com/engine/install). it'll be `docker compose`, not `docker-compose`

**Closed** 2023-06-12 23:48 UTC
Labels: bug, invalid
